//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentación.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int ID { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string Estatus { get; set; }
        public int Departamento { get; set; }
        public int Cargo { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Departamentos Departamentos { get; set; }
    }
}
